image: 'rust:latest'

stages:
  - build
  - test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt

before_script:
  - apt-get update -yq
  - rustup component add clippy
  - rustc --version
  - cargo --version

build-linux:
  stage: build
  script:
    - cargo build
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/

test:
  stage: test
  script:
    - cargo test

clippy:
  stage: test
  script:
    - cargo clippy

cache:
  paths:
    - apt/
    - cargo/
    - target/
