[package]
name = "otaws"
version = "0.1.0"
authors = ["Umut Durak <umut.durak@tu-clausthal.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terrain_server = { path = "../libs/terrain_server" }
